# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('profile_picture', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
            ],
        ),
    ]
