# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 22:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenceapi', '0003_auto_20170121_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofile',
            name='personality',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
