# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presenceapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='facebookprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='facebookprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='facebookprofile',
            name='user_name',
        ),
        migrations.AddField(
            model_name='facebookprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facebookprofile',
            name='access_token',
            field=models.CharField(max_length=255),
        ),
    ]
