# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 15:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenceapi', '0002_auto_20170121_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofile',
            name='likes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='facebookprofile',
            name='tagged_places',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
