# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenceapi', '0005_facebookprofile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookprofile',
            name='profile_picture',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
